version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
          update_type: "in_range"
    version_requirement_updates: "auto"
